version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - nvick
  ignore:
  - dependency-name: simplecov
    versions:
    - ">= 0.18.a, < 0.19"
  - dependency-name: simplecov
    versions:
    - ">= 0.19.a, < 0.20"
  - dependency-name: devise_invitable
    versions:
    - 2.0.4
  - dependency-name: bootsnap
    versions:
    - 1.7.3
  - dependency-name: twilio-ruby
    versions:
    - 5.46.1
    - 5.47.0
    - 5.48.0
    - 5.49.0
    - 5.50.0
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
