---
version: '3.0'

services:
  code:
    build:
      context: ./docker/ruby
      args:
        - RUBY_VERSION=3.0.5
        - NODE_VERSION=18
        - INSTALL_PG_CLIENT=true
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - .:/workspaces/scheduler
      - gems:/gems
    user: ruby
    tty: true
    stdin_open: true
    depends_on:
      - redis
      - postgres
    command: tail -f /dev/null
    environment:
      SEED_ADMIN_EMAIL: ${SEED_ADMIN_EMAIL}
      SEED_ADMIN_PASSWORD: ${SEED_ADMIN_PASSWORD}
      SELENIUM_REMOTE_HOST: selenium
      BOOTSNAP_CACHE_DIR: /gems/bootsnap
      REDIS_URL: redis://redis:6379/0
      REDIS_HOST: redis
